// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"modak/send-notification/v1/internal"
	"modak/send-notification/v1/internal/uc"
)

// Injectors from wire.go:

// Initialize method to initialize wire
func Initialize() (*internal.Handler, error) {
	sessionProvider := newAWSSessionProvider()
	dynamoAPI := newDynamoDBProvider(sessionProvider)
	rateLimitRulesRepositoryInterface := newRateLimitRulesRepositoryProvider(dynamoAPI)
	rateLimitCacheRepositoryInterface := newRateLimitCacheRepositoryProvider(dynamoAPI)
	validateRateLimitUC := uc.NewValidateRateLimitUC(rateLimitRulesRepositoryInterface, rateLimitCacheRepositoryInterface)
	sesapi := newSESProvider(sessionProvider)
	emailServiceInterface := newEmailServiceProvider(sesapi)
	sendNotificationUC := uc.NewSendNotificationUC(emailServiceInterface)
	loggerInterface := newLoggerProvider()
	handler := internal.NewHandler(validateRateLimitUC, sendNotificationUC, loggerInterface)
	return handler, nil
}
